# Base image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY ./app .
COPY scripts/entrypoint.sh .

# Collect static files
# RUN python manage.py collectstatic --no-input

# Run migrations
# RUN python manage.py migrate

# Expose port for Gunicorn
EXPOSE 8000

# Start Gunicorn
# CMD ["gunicorn", "--bind", "0.0.0.0:8000", "my_fight.wsgi.application"]
